### ISSUE TITLE
Code Review for @wutdequack

### ISSUE THREAD

**Issue by kewenlok** [AY2122S1-CS2113-T16-2/tp#141]
Hi @wutdequack, please find the following code review for your code:

1. Since you are using a counter for the purpose of counting the index, would it be better if you use a for-loop instead?

<img width="625" alt="Screenshot 2021-10-28 at 8 59 39 PM" src="https://user-images.githubusercontent.com/70790702/139260174-0d71e119-d94d-4761-acd4-9e8e6c72b603.png">

2. Would it be better if you change the magic literal to a constant?

<img width="483" alt="Screenshot 2021-10-28 at 9 03 31 PM" src="https://user-images.githubusercontent.com/70790702/139260864-1291adae-c3be-4dd5-85a8-ae96553a3f26.png">

3. Should containers' names be in plural form (eg. `medicineMappings`?

<img width="619" alt="Screenshot 2021-10-28 at 9 05 18 PM" src="https://user-images.githubusercontent.com/70790702/139261297-0973e12b-8db9-4b23-ae5c-468a29c5adf4.png">

4. Is it better to group the generic category of the constants at the front and then the more specific name? For example, `MESSAGE_GOODBYE`, and `MESSAGE_ENTER_RISK_LEVEL`.

<img width="838" alt="Screenshot 2021-10-28 at 9 08 58 PM" src="https://user-images.githubusercontent.com/70790702/139261909-bcc8bb17-0a4e-44af-b2ea-487b6bb511e2.png">

**Comment by wutdequack** [comment]
Thanks @kewenlok for the comments. The feedback is valid and I have addressed the concerns. Cheers :)
