### ISSUE TITLE
[PE-D] Suggestion to add save function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T16-2/tp#164]
Given that this is a records for patients, should a save function be added so the user does not have to keep re-entering the information every time the programme terminates?

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Yitching/ped#4

**Comment by wutdequack** [comment]
This has been added, but it is not reflected in the User Guide. Will add it to make it clear to users.
