### ISSUE TITLE
[PE-D] Unintuitive command tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T16-2/tp#165]
![image.png](https://raw.githubusercontent.com/Yitching/ped/main/files/b401f021-bd53-4058-8fec-1df9670e5212.png)

![image.png](https://raw.githubusercontent.com/Yitching/ped/main/files/47d7cf74-728e-4712-943a-f8ea7c13b1ae.png)

Could it be a bit confusing that when adding elderly, the username of the elderly is written as u/[username] and the name is name/[name] but when performing all the other operations like viewing med and adding med, the tag used is n/[username] instead of u/[username]

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Yitching/ped#5

**Comment by wutdequack** [comment]
This has been noted and fixed in the recent commit
