### ISSUE TITLE
[PE-D] The format for inputting usernames is not consistent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T16-2/tp#190]
![image.png](https://raw.githubusercontent.com/fansxx/ped/main/files/454c6cb2-8d8f-4203-98f0-efb42588cbd9.png)

Sometimes, `u/` is used to specify usernames and sometimes `n/` is used. It makes the user confused to which format to follow for which command.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: fansxx/ped#9

**Comment by wutdequack** [comment]
This has been fixed in the latest 2 commits.
